# Generated by Django 6.0.3 on 2026-03-24 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actes", "0001_initial"),
        ("centres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeCopie",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("reference", models.CharField(max_length=30, unique=True)),
                ("demandeur_nom", models.CharField(max_length=200)),
                ("demandeur_cin", models.CharField(blank=True, max_length=30)),
                ("demandeur_lien", models.CharField(blank=True, max_length=100)),
                (
                    "type_copie",
                    models.CharField(
                        choices=[
                            ("COPIE_INTEGRALE", "Copie intégrale"),
                            ("EXTRAIT_AVEC_FILIATION", "Extrait avec filiation"),
                            ("EXTRAIT_SANS_FILIATION", "Extrait sans filiation"),
                            ("BULLETIN", "Bulletin"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "canal",
                    models.CharField(
                        choices=[("GUICHET", "Guichet"), ("EN_LIGNE", "En ligne")],
                        max_length=10,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE_PAIEMENT", "En attente de paiement"),
                            ("PAYEE", "Payée"),
                            ("EN_COURS", "En cours de traitement"),
                            ("DELIVREE", "Délivrée"),
                            ("REJETEE", "Rejetée"),
                        ],
                        default="EN_ATTENTE_PAIEMENT",
                        max_length=25,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                ("date_livraison", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_copie",
                        to="actes.acte",
                    ),
                ),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="demandes_copie",
                        to="centres.centre",
                    ),
                ),
            ],
            options={
                "db_table": "demandes_copie",
                "ordering": ["-date_demande"],
            },
        ),
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "montant",
                    models.DecimalField(decimal_places=2, default=500.0, max_digits=10),
                ),
                ("devise", models.CharField(default="XOF", max_length=5)),
                (
                    "moyen",
                    models.CharField(
                        choices=[
                            ("MTN_MONEY", "MTN Money"),
                            ("ORANGE_MONEY", "Orange Money"),
                            ("WAVE", "Wave"),
                            ("ESPECES", "Espèces"),
                            ("VIREMENT", "Virement"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("CONFIRME", "Confirmé"),
                            ("ECHOUE", "Échoué"),
                            ("REMBOURSE", "Remboursé"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                ("reference_externe", models.CharField(blank=True, max_length=100)),
                ("date_paiement", models.DateTimeField(blank=True, null=True)),
                (
                    "recu_numero",
                    models.CharField(blank=True, max_length=50, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "demande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiement",
                        to="paiements.demandecopie",
                    ),
                ),
            ],
            options={
                "db_table": "paiements",
                "ordering": ["-created_at"],
            },
        ),
    ]
