# Generated by Django 6.0.3 on 2026-03-24 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("territoire", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Centre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=150)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("SOUS_PREFECTURE", "Sous-Préfecture"),
                            ("MAIRIE", "Mairie"),
                        ],
                        max_length=20,
                    ),
                ),
                ("adresse", models.TextField(blank=True)),
                ("telephone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("actif", models.BooleanField(default=True)),
                ("date_creation", models.DateField()),
                ("date_fermeture", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "localite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="centres",
                        to="territoire.localite",
                    ),
                ),
            ],
            options={
                "db_table": "centres",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="RattachementVillage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
                ("motif", models.CharField(blank=True, max_length=255)),
                ("decret_ref", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "centre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rattachements",
                        to="centres.centre",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rattachements",
                        to="territoire.village",
                    ),
                ),
            ],
            options={
                "db_table": "rattachements_village",
                "ordering": ["-date_debut"],
            },
        ),
    ]
