# Generated by Django 6.0.3 on 2026-03-24 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acte",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "numero_national",
                    models.CharField(blank=True, max_length=40, unique=True),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("NAISSANCE", "Naissance"),
                            ("MARIAGE", "Mariage"),
                            ("DECES", "Décès"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("BROUILLON", "Brouillon"),
                            ("VALIDE", "Validé"),
                            ("VERROUILLE", "Verrouillé"),
                            ("ANNULE", "Annulé"),
                        ],
                        default="BROUILLON",
                        max_length=15,
                    ),
                ),
                ("date_evenement", models.DateField()),
                ("date_enregistrement", models.DateTimeField(auto_now_add=True)),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("hash_contenu", models.CharField(blank=True, max_length=64)),
                ("observations", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "actes",
                "ordering": ["-date_evenement"],
            },
        ),
        migrations.CreateModel(
            name="MentionMarginale",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "type_mention",
                    models.CharField(
                        choices=[
                            ("MARIAGE", "Mariage"),
                            ("DIVORCE", "Divorce"),
                            ("DECES", "Décès"),
                            ("RECONNAISSANCE", "Reconnaissance"),
                            ("ADOPTION", "Adoption"),
                            ("RECTIFICATION", "Rectification"),
                        ],
                        max_length=20,
                    ),
                ),
                ("acte_source_ref", models.CharField(blank=True, max_length=40)),
                ("date_mention", models.DateField()),
                ("contenu", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "mentions_marginales",
                "ordering": ["-date_mention"],
            },
        ),
        migrations.CreateModel(
            name="ActeDeces",
            fields=[
                (
                    "acte",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="detail_deces",
                        serialize=False,
                        to="actes.acte",
                    ),
                ),
                ("heure_deces", models.TimeField(blank=True, null=True)),
                ("lieu_deces", models.CharField(blank=True, max_length=200)),
                ("cause_deces", models.CharField(blank=True, max_length=500)),
                ("declarant_nom", models.CharField(max_length=200)),
                ("declarant_prenoms", models.CharField(max_length=200)),
                ("declarant_lien", models.CharField(blank=True, max_length=50)),
                ("declarant_cin", models.CharField(blank=True, max_length=30)),
                ("acte_naissance_ref", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "db_table": "actes_deces",
            },
        ),
        migrations.CreateModel(
            name="ActeMariage",
            fields=[
                (
                    "acte",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="detail_mariage",
                        serialize=False,
                        to="actes.acte",
                    ),
                ),
                ("regime_matrimonial", models.CharField(blank=True, max_length=100)),
                ("temoin1_nom", models.CharField(blank=True, max_length=200)),
                ("temoin1_cin", models.CharField(blank=True, max_length=30)),
                ("temoin2_nom", models.CharField(blank=True, max_length=200)),
                ("temoin2_cin", models.CharField(blank=True, max_length=30)),
                ("officiant_nom", models.CharField(blank=True, max_length=200)),
                (
                    "acte_naissance_epoux_ref",
                    models.CharField(blank=True, max_length=40),
                ),
                (
                    "acte_naissance_epouse_ref",
                    models.CharField(blank=True, max_length=40),
                ),
            ],
            options={
                "db_table": "actes_mariage",
            },
        ),
        migrations.CreateModel(
            name="ActeNaissance",
            fields=[
                (
                    "acte",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="detail_naissance",
                        serialize=False,
                        to="actes.acte",
                    ),
                ),
                ("heure_naissance", models.TimeField(blank=True, null=True)),
                ("ordre_naissance", models.PositiveSmallIntegerField(default=1)),
                (
                    "poids_naissance",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                ("etablissement", models.CharField(blank=True, max_length=200)),
                ("declarant_nom", models.CharField(max_length=200)),
                ("declarant_prenoms", models.CharField(max_length=200)),
                ("declarant_lien", models.CharField(blank=True, max_length=50)),
                ("declarant_cin", models.CharField(blank=True, max_length=30)),
            ],
            options={
                "db_table": "actes_naissance",
            },
        ),
    ]
