# Generated by Django 6.0.3 on 2026-03-24 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actes", "0001_initial"),
        ("centres", "0001_initial"),
        ("individus", "0001_initial"),
        ("territoire", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="acte",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actes_crees",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="acte",
            name="centre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actes",
                to="centres.centre",
            ),
        ),
        migrations.AddField(
            model_name="acte",
            name="individu",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="actes",
                to="individus.individu",
            ),
        ),
        migrations.AddField(
            model_name="acte",
            name="superviseur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="actes_valides",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="acte",
            name="village",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="territoire.village",
            ),
        ),
        migrations.AddField(
            model_name="mentionmarginale",
            name="acte",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mentions",
                to="actes.acte",
            ),
        ),
        migrations.AddField(
            model_name="mentionmarginale",
            name="agent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="mentionmarginale",
            name="centre_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="centres.centre",
            ),
        ),
        migrations.AddField(
            model_name="actemariage",
            name="epouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mariages_epouse",
                to="individus.individu",
            ),
        ),
        migrations.AddField(
            model_name="actemariage",
            name="epoux",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="mariages_epoux",
                to="individus.individu",
            ),
        ),
        migrations.AddIndex(
            model_name="acte",
            index=models.Index(
                fields=["individu", "nature"], name="actes_individ_37475b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acte",
            index=models.Index(
                fields=["centre", "nature"], name="actes_centre__29d232_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="acte",
            index=models.Index(fields=["statut"], name="actes_statut_0a916c_idx"),
        ),
        migrations.AddIndex(
            model_name="acte",
            index=models.Index(
                fields=["numero_national"], name="actes_numero__88005c_idx"
            ),
        ),
    ]
