# Generated by Django 6.0.3 on 2026-03-27 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actenaissance',
            name='nationalite_mere',
            field=models.CharField(blank=True, default='CI', max_length=50),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='nationalite_pere',
            field=models.CharField(blank=True, default='CI', max_length=50),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='nom_mere',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='nom_pere',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='prenoms_mere',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='prenoms_pere',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='profession_mere',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='actenaissance',
            name='profession_pere',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
