# Generated by Django 6.0.3 on 2026-03-24 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centres", "0001_initial"),
        ("territoire", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Individu",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nin", models.CharField(max_length=20, unique=True)),
                ("nom", models.CharField(max_length=100)),
                ("prenoms", models.CharField(max_length=200)),
                (
                    "sexe",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1
                    ),
                ),
                ("date_naissance", models.DateField()),
                (
                    "lieu_naissance_libelle",
                    models.CharField(blank=True, max_length=200),
                ),
                ("nationalite", models.CharField(default="Ivoirienne", max_length=100)),
                ("hash_biographique", models.CharField(max_length=64, unique=True)),
                ("est_decede", models.BooleanField(default=False)),
                ("date_deces", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "centre_naissance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individus_nes",
                        to="centres.centre",
                    ),
                ),
                (
                    "lieu_naissance_village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individus_nes",
                        to="territoire.village",
                    ),
                ),
            ],
            options={
                "db_table": "individus",
                "ordering": ["nom", "prenoms"],
            },
        ),
        migrations.CreateModel(
            name="Filiation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("PERE", "Père"), ("MERE", "Mère")], max_length=10
                    ),
                ),
                ("nom_libelle", models.CharField(blank=True, max_length=200)),
                ("prenoms_libelle", models.CharField(blank=True, max_length=200)),
                (
                    "enfant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filiations",
                        to="individus.individu",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enfants",
                        to="individus.individu",
                    ),
                ),
            ],
            options={
                "db_table": "filiations",
            },
        ),
        migrations.AddIndex(
            model_name="individu",
            index=models.Index(
                fields=["nom", "prenoms"], name="individus_nom_f40f81_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="individu",
            index=models.Index(
                fields=["date_naissance"], name="individus_date_na_76fc49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="individu",
            index=models.Index(
                fields=["hash_biographique"], name="individus_hash_bi_18e23f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filiation",
            unique_together={("enfant", "role")},
        ),
    ]
