# Generated by Django 6.0.3 on 2026-03-24 15:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("actes", "0001_initial"),
        ("centres", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationInterCentre",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type_evenement", models.CharField(max_length=50)),
                ("payload", models.JSONField(default=dict)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("EN_ATTENTE", "En attente"),
                            ("ENVOYEE", "Envoyée"),
                            ("ACQUITTEE", "Acquittée"),
                            ("ECHOUEE", "Échouée"),
                        ],
                        default="EN_ATTENTE",
                        max_length=15,
                    ),
                ),
                ("tentatives", models.PositiveSmallIntegerField(default=0)),
                ("date_envoi", models.DateTimeField(blank=True, null=True)),
                ("date_acquittement", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "acte_cible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications_recues",
                        to="actes.acte",
                    ),
                ),
                (
                    "acte_declencheur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications_emises",
                        to="actes.acte",
                    ),
                ),
                (
                    "centre_destinataire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications_recues",
                        to="centres.centre",
                    ),
                ),
                (
                    "centre_emetteur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notifications_emises",
                        to="centres.centre",
                    ),
                ),
            ],
            options={
                "db_table": "notifications_intercentre",
                "ordering": ["-created_at"],
            },
        ),
    ]
